### ISSUE TITLE
`Fixture` feature for selecting an environment to run the integration tests

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#118]
Developing `Fixture` feature settings which allow developers to easily switch between the integration tests In-memory environment to `develop` (live) environment upon demand.

The difference between the environments for the configuration service :

`In-memory` - Vault and DB are `mocked` there
`develop` / live - Vault and DB `aren't mocked` there

**Comment by stingion** [comment]
Pull requests for task:

1) https://github.com/scalecube/scalecube-organization-service/pull/135
2) https://github.com/scalecube/scalecube-configuration-service/pull/131

**Comment by stingion** [comment]
https://github.com/scalecube/scalecube-configuration-service/pull/131
