### ISSUE TITLE
Versions in Key Management 

### ISSUE THREAD

**Issue by dudikrisher** [scalecube/scalecube-configuration-service#138]
As a configuration service consumer, I would like to keep all the data in the configuration service by having versions mechanism in the service.

- [x] Rename 
  - [x] `save` to `createEntry` 
  - [x] `fetch` to `readEntry` 
  - [x] `delete` to `deleteEntry` 
  - [x] `entries` to `readList` 
- [x] add validation  `createEntry` that key is not already exists. (this will make this method Insert only > https://take.ms/RPURp
- [x] on `createEntry` method the response will include the version --> always 1 `{version:1}` > https://take.ms/PIEqf
- [x] Add new method named `updateEntry` - this will be used for updating existing entries > https://take.ms/5lgIL  / https://take.ms/0yn6S
- [x] on `updateEntry` method, nothing will be over written, only the version will increase by 1. The response will include the version --> for example : `{version:5}` > https://take.ms/5lgIL
- [x] on `readList` and `readEntry` a new optional request parameter will be added named `version`. 
**In `readEntry`:**  
- If not empty then the system will look for that version, if found this will be returned > https://take.ms/Hkjvl
- If empty then the latest version will be returned > https://take.ms/k3SGQ
- if not exists then error message will be returned saying: Requested `version` not found > https://take.ms/PHUEm 
**In `readList`:**
- If not empty then the system will look for that version, if found this will be returned > https://take.ms/lXdnC
- If empty then the latest version will be returned > https://take.ms/DSQHe
- If not exists the empty array will be returned > https://take.ms/sI81It
- [x] Add a new method named `readEntryHistroy` - this will be used to get all the history for a specific key > https://take.ms/RirAE
- [x] Update API doc > https://github.com/scalecube/scalecube-configuration-service/wiki/OM2-Configuration-Service-API-Document

`Bug to fix:`
- [x] #144 > https://take.ms/g3Q8I
- [x] #145 > https://take.ms/K6uNN
- [x] #158  
- [x] #162  > https://take.ms/5p9gDE
- [x] #164

**Comment by stingion** [comment]
https://github.com/scalecube/scalecube-configuration-service/pull/143

**Comment by stingion** [comment]
Validation for repos and key names should be considered

**Comment by stingion** [comment]
Consider trimming for repository and key names

**Comment by PavloEsco** [comment]
Tested OK
