### ISSUE TITLE
readList api call returns the error "View keys/by_keys does not exist"

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#145]
Precondition > 
1. Owner/Admin apiKey is stored in the related Organization
2. Related Repo was created

STR > `/configuration/readList` > {"errorCode":500,"errorMessage":"View keys/by_keys does not exist."}}

**Comment by stingion** [comment]
Should be created view in index of DB

**Comment by PavloEsco** [comment]
fixed by adding a simple setting in DB for `view`
