### ISSUE TITLE
recently created keys and related values weren't returned upon 'readList' API call was done

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#158]
**Environment** > `develop`
`First path`
STR
1. createRepository > "repo-A"
2. createEntry > repo-A, key-B, value: {"JSON-DATA":"new"}
3. readList (without version)> repo-A

**AR**: empty array > https://take.ms/TvSAC
**ER**: d":[{"value":{"JSON-DATA":"new"},"key":"key-B"}]}

`Second path`

**Precondition** > entire data with old keys already stored in DB (look on `First path`)

STR:
1. createEntry > repo-1, key-1, value: {val-1}
2. createEntry >repo-1, key-2, value: {val-1}
3. updateEntry >repo-1, key-2 > value:  [{val-1}, {val-2}]
4. readHistory > repo-1, key-2 > value: [{val-1}, {val-2}]
5. readList > repo-1
6. readList > repo-1

AR: step#5 > entire data **(precondition)** with old keys and values was returned without new keys and last versions of them. > https://take.ms/P2IKY Only in step#6 returned all the stored keys with last versions 

ER:  all the stored keys with last versions should be returned from the first api call `readList` (which been done in step#5)

**Comment by stingion** [comment]
Pull request with fixes: https://github.com/scalecube/scalecube-configuration-service/pull/165

**Comment by stingion** [comment]
Merged to `develop` branch

**Comment by PavloEsco** [comment]
Tested OK
