### ISSUE TITLE
remove ORG-ID from errorMessage fro key duplication via 'createEntry' method

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#160]
ER > https://take.ms/XY9wm

**Comment by stingion** [comment]
done in scope of pull request:
https://github.com/scalecube/scalecube-configuration-service/pull/156

**Comment by PavloEsco** [comment]
Tested OK > https://take.ms/SDjoL

**Comment by stingion** [comment]
Merged to `develop` branch

**Comment by PavloEsco** [comment]
Tested OK 'develop'
