### ISSUE TITLE
iterator returned null on 'readEntryHistory' API call if any stored version consist a 'null' value

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#162]
**Precondition** > valid API key and related repository already created

STR
1. createEntry > repo: "A", key:"key-1", value: `null`
2. readEntryHistory >  repo: "A", key:"key-1"

**AR:** {"errorCode":500,"errorMessage":"Please specify 'key'"}} > https://take.ms/LPMQO
**ER:** array with all stored values is returned incl `null` value

**Comment by stingion** [comment]
In scope of pull request: https://github.com/scalecube/scalecube-configuration-service/pull/167

**Comment by PavloEsco** [comment]
Tested Ok on `Develop`
