### ISSUE TITLE
support the 'JsonArray' for 'createEntry' method

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#163]
Currently, the supported data type for `createEntry` method is only `string`
 
We need to support the JsonArray > https://take.ms/N8rpy

**Comment by dudikrisher** [comment]
@PavloPetrina why do we need this?

**Comment by PavloEsco** [comment]
> @PavloPetrina why do we need this?

In this case, you'll be able to send an array of objects (strings) which in our case could be the instruments and calendars which brings some order to stored data, here is the example > https://www.quora.com/What-is-the-difference-between-json-array-and-json-object
Otherwise, if you don't want to support  this `list` we should exclude it from `updateEntry`  method as we can update the existing key/value with JsonArray

**Comment by dudikrisher** [comment]
each instrument is a single key. I don't see the use case we need this.
Please explain.

**Comment by stingion** [comment]
Made in scope of https://github.com/scalecube/scalecube-configuration-service/issues/162

**Comment by stingion** [comment]
@dudikrisher I made the support (create and update) for array, it's not problem.

**Comment by PavloEsco** [comment]
> each instrument is a single key. I don't see the use case we need this.
> Please explain.

For a now - yes indeed but I gave an example which could be relevant not only for our purposes (Exchange) but also for other consumers of Configuration service. I'm not insisting on this Array just wanted to think in the scope of potential customers.

**Comment by dudikrisher** [comment]
seems this was already done in 162.
Please close this issue.
Thanks

**Comment by PavloEsco** [comment]
Tested Ok on `develop`

**Comment by PavloEsco** [comment]
> seems this was already done in 162.
> Please close this issue.
> Thanks

Will close when all the regression will be done in `master`
