### ISSUE TITLE
return the errorMessage if the Repository doesn't exists upon the 'readList' API call performed

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#164]
STR
readList > specify the repo which doesn't exist 

AR > https://take.ms/1ineU
ER > {"errorCode":500,"errorMessage":"`Repository 'non-existent-repo'` not found"}

**Comment by stingion** [comment]
Fix: https://github.com/scalecube/scalecube-configuration-service/pull/165

**Comment by stingion** [comment]
Pull request with enhancement: https://github.com/scalecube/scalecube-configuration-service/pull/166

**Comment by PavloEsco** [comment]
Tested OK
