### ISSUE TITLE
Wrap the data parsing error for readEntry&readList methods

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#174]
{
	"q":"/configuration/readEntry",
	"sid": 1,
	"d":{
                "apiKey": "API-TOKEN",
                "repository": "specifiedRepoName",
                "key": "specifiedKeyName"
                "version": `"sfosihfjoishfuishfuishiu"`
        }
}

{
	"q":"/configuration/readList",
	"sid": 1,
	"d":{
                 "apiKey": "API-KEY",
                 "repository": "REPO-NAME"
                 "version": `"TTRETETETTETE"`
        }
}

**AR** 
> Failed to decode data on message q=/configuration/`readEntry`
 Failed to decode data on message q=/configuration/`readList`

**ER** >error message: ` Version must be a positive number`

**Comment by stingion** [comment]
Made in scope of IT for versioning:
Implement new+update existing integration tests for Configuration service #124
